### ISSUE TITLE
More controlled handling of exceptions needed

### ISSUE THREAD

**Issue by judgej** [spresnac/laravel-create-user-cli#9]
This is great when automated creation of users us required for a deploy. We create base users through ansible when deploying to ensure a known set of users are available.

However, if the user already exists or some other validation error occurs, the command issues the full exception dump and exits with a "1" result.

I would propose that instead of a full exception dump, just the exception message is displayed as an error. For users that already exist, maybe even a specific result code so it can be handled in the deploy scripts as an ignorable error if necessary.

Is that a feature that fits with your plans for this package?

**Comment by spresnac** [comment]
This sound pretty cool, thanks for this idea.
Do you have any specific input for me regarding for a result code?

So, I do not know exactly when I will get to this issue, but feel free to add your code as pull request 🤩
Otherwise: I will do it, but cannot tell a timeline for this.

**Comment by judgej** [comment]
Yeah, happy to do PR.

How a duplicate user is handled is up for options I guess. The use-case is that a deploy script will create a user if the user does not already exist. So there are a number of approaches:

* Find out if the user already exists first, and only run this command if the user does not exist. Another command could be written for this.
* Treat a user already existing as not an error; just return a "0" and a message indicating this. Maybe this could be optional `--suppress-already-exists`
* Return a different code for a user that already exists: 0 for created, 1 for unexpected errors, 2 for user not created because they already exist. This feels like an approach less often taken.
* Maybe if the user already exists, treat this as an update. Again, could be optonal `--create --update` to allow either a create of a user or an update.
* Any other approach. Just trying to weigh up simple/quick/intuitive/best practice.

**Comment by spresnac** [comment]
This reads pretty nice and would like to give my 2 cents for it 😉

* Let’s return instead of just 1,2,3,... the corresponding HTTP codes:
  * 201 ⇾ The user was created
  * 409 ⇾ There was a conflict on creating the user (user already exists, no overwrite)
  * ...

* More options:
  * Already in is a `force` option
    * when used, a user will be upserted (created or updated when existing)
    * when not used, an error 409 will be returned
  * So, with this in mind, I do not see any new options needed.

Did I miss/forgot something?

**Comment by spresnac** [comment]
Returning with HTTP codes would imply to make this a new major version of this package.

**Comment by judgej** [comment]
Returning HTTP codes is not how Linux scripts work as a standard. They return "0" for success and a non-zero for failure. Returning non-zero for a success would break a lot of things and be totally unexpected. I can't remember the range of the values - used to be 8 bit (0-255) a long time ago, maybe a signed integer now. Breaking with the convention is certainly not the way to go IMO.

**Comment by spresnac** [comment]
Ok, it was just a proposal 😉
Let's do it the "correct" way, 0 is for `All good`, other values to be defined 💪

**Comment by spresnac** [comment]
So, me personally would prefer to keep it as simple as possible. I will stick on my believes not to implement more options than needed. IMHO the `force` option would be enough.

My Question now: Do you code this? Just to prevent two people working on the same thing 😉

**Comment by spresnac** [comment]
New version fixes this: https://github.com/spresnac/laravel-create-user-cli/releases/tag/1.0.5
